[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "run_alphafold3"
version = "0.0.1"
authors = [
  { name = "Andrey Rozenberg", email = "alephreish@gmail.com" }
]
description = "AlphaFold3 wrapper"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3",
    "Operating System :: OS Independent",
]
dependencies = [
    "gemmi==0.7.3",
    "tqdm==4.67.2",
    "biopython==1.85"
]
[project.urls]
"Homepage" = "https://github.com/BejaLab/run_alphafold3"
"Bug Tracker" = "https://github.com/BejaLab/run_alphafold3/issues"

[project.scripts]
alphafold3_init = "run_alphafold3.job_init:cli"
alphafold3_predict = "run_alphafold3.job_predict:cli"
alphafold3_complex = "run_alphafold3.job_complex:cli"
alphafold3_search = "run_alphafold3.job_search:cli"
alphafold3_search_mod = "run_alphafold3.job_search_mod:cli"
alphafold3_json = "run_alphafold3.job_json:cli"
alphafold3_select = "run_alphafold3.job_select:cli"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"run_alphafold3.mods" = ["a3m/*.a3m", "cif/*.cif", "*.csv"]
